config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'authors/index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get 'relatives', to: 'relatives#index'
  get 'relatives ', to: 'relatives#show'
  get 'relatives/new',to: 'relatives#new',as: :new_relative
  post 'relatives', to: 'relatives#create', as: :create_relative
  delete 'relatives/:id',to: 'relatives#destroy',as: :destroy_relative
  get 'relatives/:id/edit', to: 'relatives#edit', as: :edit_relative
  patch 'relatives/:id', to: 'relatives#update', as: :update_relative
  get 'relatives/:id', to: 'relatives#show', as: :relative
  
  get 'students', to: 'students#index'
  get 'students ', to: 'students#show'
  get 'students/new',to: 'students#new',as: :new_student
  post 'students', to: 'students#create', as: :create_student
  delete 'students/:id',to: 'students#destroy',as: :destroy_student
  get 'students/:id/edit', to: 'students#edit', as: :edit_student
  patch 'students/:id',to: 'students#update',as: :update_student
  get 'students/:id',to: 'students#show',as: :student

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
  end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many  :appointments
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appontments
  end

app/models/relative.rb
class Relative < ApplicationRecord
    validates:name , presence:true
    validates:age , presence:true
end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index

  end
end

app/controllers/college_controller.rb
class CollegeController < ApplicationController
  def name:string
  end

  def enrollno:integer
  end

  def standard:integer
  end

  def subject:string
  end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  http_basic_authenticate_with name: "mitesh", password: "88999976", except: [:index, :show]

  def index
    @relatives =Relative.all  
  end

  def new
    @relative = Relative.new  
  end

  def create
    @relative = Relative.new(relative_params)
    if @relative.save
      redirect_to relatives_path
    else
      render :new
    end
  end

  def edit
    @relative = Relative.find(params[:id])
  end

  def update
    @relative = Relative.find(params[:id])
    @relative.update(relative_params)
    redirect_to relatives_path
  end

  def destroy
    @relative = Relative.find(params[:id])
    @relative.destroy
    redirect_to relatives_path
  end

  def show
    @relative = Relative.find(params[:id])
  end

  private
  def relative_params
    params.require(:relative).permit(:name,:age)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if@student.save
      redirect_to students_path
    else
      render:new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to students_path
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  def show
    @student = Student.find(params[:id])
  end

  private
  def student_params
    params.require(:student).permit(:name,:enroll_no,:standard,:email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/college_helper.rb
module CollegeHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/relatives/edit.html.erb
<center>
  Update Relatives
  <%= form_for @relative do |form| %>
    <%= form.text_field :name %><br>
    <%= form.text_field :age %><br>
    <%= form.check_box :age %><br>
    <%= form.label :age, "I m yonger" %><br>
    <%= form.select :age, ["1", "18", "36"] %> <hr>  
    <%= form.radio_button :age,  "1"%><br>
    <%= form.label  :age_1 , "teenage"%><br>
    <%= form.radio_button :age , "18"%><br>
    <%= form.label  :age_18 , "adult"%><br>
    <%= form.radio_button :age , "36"%><br>
    <%= form.label :age_36 , "oldage"%><br>
    <%= form.text_area :name, size: "10*5"%><br>  
    <%= form.submit %>
  <% end %>
</center>

app/views/relatives/index.html.erb
<h1>Relatives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <% @relatives.each do |relative| %>
      <tr>
        <td><%= relative.name %></td>
        <td><%= relative.age %></td>
        <td><%= link_to "edit", edit_relative_path(relative.id), method: :get %></td>
        <td><%= link_to "Delete", destroy_relative_path(relative.id),method: :delete %></td>  
        <td><%= link_to "show", relative_path(relative.id), method: :get %></td
      </tr>

    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Relative", new_relative_path %><br>
</center>
</body>
</html>

app/views/relatives/new.html.erb
<center>
  Update Relatives
  <%= form_for @relative do |form| %>
    <%= form.text_field :age %><br>
      <% @relative.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <%= form.text_field :name %><br>
    <%= form.check_box :age %><br>
    <%= form.label :age, "I m yonger" %><br>
    <%= form.select :age, ["1", "18", "36"] %> <hr>  
    <%= form.radio_button :age,  "1"%><br>
    <%= form.label  :age_1 , "teenage"%><br>
    <%= form.radio_button :age , "18"%><br>
    <%= form.label  :age_18 , "adult"%><br>
    <%= form.radio_button :age , "36"%><br>
    <%= form.label :age_36 , "oldage"%><br> 
    <%= form.text_area :name, size: "10*5"%><br> 
    <%= form.submit %><br>
  <% end %>
</center>

app/views/relatives/show.html.erb
<h1><%= @relative.name %></h1>

<h2><%= @relative.age %></h2> 

app/views/students/edit.html.erb
<center>
  Update Students
  <%= form_for @student do |form| %>
    <%= form.text_field :name %><br>
    <% @student.errors.full_messages_for(:name).each do |message| %>
      <div> <%= message %> </div>
    <% end %>

    <%= form.text_field :email %><br>
    <% @student.errors.full_messages_for(:email).each do |message| %>
      <div> <%= message %> </div>
    <% end %>

    <%= form.check_box :enroll_no %><br>  
    <%= form.label :enroll_no, "I have enrollment_no" %><br>
    <%= form.select :standard, ["4", "9", "11"] %> <hr>  
    <%= form.radio_button :standard, "4" %><br>
    <%= form.label :standard_5_8, "primary" %><br>
    <%= form.radio_button :standard, "8" %><br>
    <%= form.label :standard_9_10, "Secondary" %><br>
    <%= form.radio_button :standard, "12" %><br>
    <%= form.label :standard_10_12, "Highr-Secondary" %><br> 
    <%= form.text_area :standard, size: "10*5" %><br>
    <br><%= form.submit %>
  <% end %>
</center>

app/views/students/index.html.erb
<center>
<h2>Student</h2>
  <table>
    <tr>

    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Enroll_no</th>
      <th scope="col">Standard</th>
      <th scope="col">Email</th>
      <th scop="col">Update</th>
      <th scop="col">Detroy</th>
      <th scop="col">Show</th>
    </tr>
  </thead>
 
    <% @students.each do |student|%>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.enroll_no %></td>
        <td><%= student.standard %></td>
        <td><%= student.email %></td>
        <td><%= link_to "Edit", edit_student_path(student.id), method: :get, class: "btn btn-secondary active" %></td>
        <td><%= link_to "Delete", destroy_student_path(student.id), method: :delete, class: "btn btn-danger"%></td>  
        <td><%= link_to "Show", student_path(student.id), method: :get, class: "btn btn-secondary active" %></td>  

        </tr>  
    <% end %>
    
  </table>
  <br>
  <%= link_to "New Student", new_student_path %>
<div class="mb-3">
<select class="form-select" aria-label="Default select example">
<option selected>Open this semester menu</option>
<option value="1">One</option>
<option value="2">Two</option>
<option value="3">Three</option>
<option value="4">Four</option>
<option value="5">Five</option>
<option value="6">Six</option>
<option value="7">Seven</option>
<option value="8">Eight</option>
</select></div>


</center>

app/views/students/new.html.erb
<center>
<%= form_for @student do |form| %>
  <%= form.text_field :name , class: "form-group"%><br>
  <% @student.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <%= form.text_field :email %><br>
  <% @student.errors.full_messages_for(:email).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <%= form.check_box :enroll_no %><br>
  <%= form.label :enroll_no, "I have enrollment_no" %><br>
  <%= form.select :standard, ["4", "9", "11"] %> <hr>  
  <%= form.radio_button :standard, "4" %><br>
  <%= form.label :standard_4, "primary" %><br>
  <%= form.radio_button :standard, "8" %><br>
  <%= form.label :standard_8, "Secondary" %><br>
  <%= form.radio_button :standard, "12" %><br>
  <%= form.label :standard_12, "Highr-Secondary" %><br> 
  <%= form.text_area :standard, size: "10*5" %><br>
  <%= form.submit %>
<% end %>
</center> 

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<h2><%= @student.enroll_no %></h2>
<h3><%= @student.standard %></h3>
<h4><%= @student.email %></h4>